name: hikari
description: Dartを100%生かした（つもりの）サーバサイドWebフレームワーク
version: 0.0.1
repository: https://github.com/kentt8046/hikari
issue_tracker: https://github.com/kentt8046/hikari/issues
platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.0
  http_parser: ^4.0.0
  yaml: ^3.1.0

dev_dependencies:
  coverage: ^1.0.0
  lints: ^2.0.0
  test: ^1.16.0
